# Generated by Django 2.2.5 on 2021-07-14 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vaccin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isbn_number', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Characteristiques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vaccin', models.CharField(max_length=200)),
                ('efficacite_vaccin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conservation_vaccin_max', models.IntegerField()),
                ('conservation_vaccin_min', models.IntegerField()),
                ('prix_vaccin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'critere',
            },
        ),
        migrations.CreateModel(
            name='Effets_secondaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensibilité_au_point_injection_vaccin', models.FloatField()),
                ('douleur_au_point_injection_vaccin', models.FloatField()),
                ('céphalées_vaccin', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Posologie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dose_vaccin', models.IntegerField()),
                ('age_vaccin_max', models.IntegerField()),
                ('age_vaccin_min', models.IntegerField()),
                ('delais_vaccin', models.IntegerField()),
                ('temps_effet_vaccin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vaccin', models.CharField(max_length=200)),
                ('Characteristiques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Characteristiques')),
                ('cout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cout')),
                ('effets_secondaires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Effets_secondaires')),
                ('posologie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Posologie')),
            ],
        ),
        migrations.CreateModel(
            name='Upload_csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_csv', models.FileField(default='default.csv', null=True, upload_to='media/files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_csv', to='app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Subcritere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('critere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcriters', to='app.Critere')),
            ],
            options={
                'db_table': 'subcritere',
            },
        ),
        migrations.AddField(
            model_name='critere',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='app.Profile'),
        ),
    ]
