# Generated by Django 2.2.5 on 2021-07-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210714_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='critere',
            options={'ordering': ['-created_at']},
        ),
    ]
