# Generated by Django 3.2.5 on 2021-09-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='nom_vaccin',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='subcritere',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
