# Generated by Django 3.2.5 on 2021-09-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_promethee_file_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_csv',
            old_name='file_csv',
            new_name='path',
        ),
        migrations.AddField(
            model_name='upload_csv',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
