# Generated by Django 2.2.5 on 2021-07-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210720_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Critere')),
            ],
        ),
    ]
