# Generated by Django 3.2.5 on 2021-07-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dictionnaire', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='a',
            name='critere',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.RemoveField(
            model_name='vaccins',
            name='Characteristiques',
        ),
        migrations.RemoveField(
            model_name='vaccins',
            name='cout',
        ),
        migrations.RemoveField(
            model_name='vaccins',
            name='effets_secondaires',
        ),
        migrations.RemoveField(
            model_name='vaccins',
            name='posologie',
        ),
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='Characteristiques',
        ),
        migrations.DeleteModel(
            name='Cout',
        ),
        migrations.DeleteModel(
            name='Effets_secondaires',
        ),
        migrations.DeleteModel(
            name='Posologie',
        ),
        migrations.DeleteModel(
            name='Vaccins',
        ),
    ]
