# Generated by Django 3.2.5 on 2021-09-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210917_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_csv',
            name='path_weight',
            field=models.FileField(default='default_weight.csv', null=True, upload_to='media/files/'),
        ),
        migrations.AddField(
            model_name='upload_csv',
            name='weight',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
