# Generated by Django 3.2.5 on 2021-09-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210917_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_csv',
            old_name='weight',
            new_name='weight_names',
        ),
    ]
