# Generated by Django 3.2.5 on 2021-07-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210721_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critere',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
