# Generated by Django 3.2.5 on 2021-07-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_critere_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critere',
            name='user',
        ),
        migrations.AlterField(
            model_name='critere',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
