# Generated by Django 3.2.5 on 2021-09-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_weight_upload_csv_weight_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_csv',
            name='path',
            field=models.FileField(default='default.csv', null=True, upload_to='promethee/'),
        ),
        migrations.AlterField(
            model_name='upload_csv',
            name='path_weight',
            field=models.FileField(default='default_weight.csv', null=True, upload_to='promethee/'),
        ),
    ]
