# Generated by Django 3.2.4 on 2021-06-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
    ]
