# Generated by Django 3.2.5 on 2021-07-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210725_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critere',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
