# Generated by Django 3.2.4 on 2021-06-26 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile_file_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file_csv',
        ),
        migrations.CreateModel(
            name='Upload_csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_csv', models.FileField(default='default.csv', null=True, upload_to='media/files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_csv', to='app.profile')),
            ],
        ),
    ]
