# Generated by Django 3.2.4 on 2021-06-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210626_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.FloatField()),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
