# Generated by Django 3.2.4 on 2021-06-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='value',
            field=models.FloatField(),
        ),
    ]
