# Generated by Django 2.2.5 on 2021-07-07 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210629_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vaccin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Critere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_critere', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_subcritere', models.CharField(max_length=100)),
                ('criter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='app.Critere')),
            ],
        ),
    ]
