# Generated by Django 2.2.5 on 2021-07-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='critere',
            name='nom_critere',
        ),
        migrations.AddField(
            model_name='critere',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='critere',
            table='critere',
        ),
    ]
