# Generated by Django 2.2.5 on 2021-07-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210711_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcritere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('critere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcriters', to='app.Critere')),
            ],
            options={
                'db_table': 'subcritere',
            },
        ),
        migrations.DeleteModel(
            name='Subcriteria',
        ),
    ]
