# Generated by Django 2.2.5 on 2021-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210712_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='critere',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
